name: Build Rackify Windows

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.7"
          channel: stable

      - name: Install Flet
        run: |
          pip install --upgrade pip
          pip install --upgrade flet flet-cli

      - name: Build Windows App
        env:
          PYTHONUTF8: "1"
          PYTHONIOENCODING: "utf-8"
        run: |
          chcp 65001
          flet build windows

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rackify-Windows
          path: build/windows/**