name: Build Rackify Windows

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Flet
        run: |
          pip install flet

      - name: Build Windows App
        run: |
          flet build windows

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rackify-Windows
          path: build/windows/**